name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  test:
    name: Run Tests Before Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run tests
      run: npm run test:coverage

    - name: Run linter
      run: npm run lint

    - name: Build package
      run: npm run build

    - name: Build plugin
      run: npm run build:plugin

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build package
      run: npm run build

    - name: Build plugin
      run: npm run build:plugin

    - name: Prepare for publish
      run: npm run prepublishOnly

    - name: Verify package contents
      run: npm pack --dry-run

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: publish
    if: success()

    steps:
    - name: Notify successful publish
      run: |
        echo "✅ Successfully published expo-streamer to NPM!"
        echo "📦 Package: https://www.npmjs.com/package/expo-streamer"
        echo "🔗 Repository: https://github.com/truemagic-coder/expo-streamer"